# Multi-Language settings
t:
  english:
    title: "Mariangel and James"
    subtitle: "July 25, 2021"
    description: "Save the date: July 25, 2021 | New Haven, CT"
    getstarted: ""
  español:
    title: "Mariangel y James"
    subtitle: "25 de Julio de 2021"
    description: "Guarda la fecha: 25 de Julio de 2021 | New Haven, CT"
    getstarted: "!"

# site settings
email: james.dossgollin@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mariandjames.us" # the base hostname & protocol for your site
author: James Doss-Gollin

# icon
logo_icon: /assets/images/logos/logo.ico

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 100 # this could potentially limit the number of posts

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jdossgollin
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
